### ISSUE TITLE
randn生成矩阵经过运算后为什么和correct_socres一致？

### ISSUE THREAD

**Issue by MingzhouZhang** [Halfish/cs231n#3]
cs231n/assignment1/two_layer_net.ipynb的Forward pass: compute scores中，correct_scores怎么来的，怎么能保证通过随机生成的矩阵经过运算后，能和corret_scores基本相同？

**Comment by Halfish** [comment]
那个是课程设计者给的参考答案。另外 np.random.seed() 可以固定生成随机数的种子。

**Comment by MingzhouZhang** [comment]
哦，原来是固定的，谢谢。
